//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeopleWithResearch.Resources.Strings
{
    using System;
    using System.Reflection;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {}

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PeopleWithResearch.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        /// <summary>AppName</summary>
        public static string AppName
        {
            get { return ResourceManager.GetString("AppName", resourceCulture); }
        }

        /// <summary>MainPage_ResearchCode</summary>
        public static string MainPage_ResearchCode
        {
            get { return ResourceManager.GetString("MainPage_ResearchCode", resourceCulture); }
        }

        /// <summary>MainPage_ThankYou</summary>
        public static string MainPage_ThankYou
        {
            get { return ResourceManager.GetString("MainPage_ThankYou", resourceCulture); }
        }

        /// <summary>MainPage_PasteInstructions</summary>
        public static string MainPage_PasteInstructions
        {
            get { return ResourceManager.GetString("MainPage_PasteInstructions", resourceCulture); }
        }

        /// <summary>MainPage_PasteButton</summary>
        public static string MainPage_PasteButton
        {
            get { return ResourceManager.GetString("MainPage_PasteButton", resourceCulture); }
        }

        /// <summary>MainPage_LanguageButton</summary>
        public static string MainPage_LanguageButton
        {
            get { return ResourceManager.GetString("MainPage_LanguageButton", resourceCulture); }
        }

        /// <summary>SelectLang_Title</summary>
        public static string SelectLang_Title
        {
            get { return ResourceManager.GetString("SelectLang_Title", resourceCulture); }
        }

        /// <summary>SelectLang_Description</summary>
        public static string SelectLang_Description
        {
            get { return ResourceManager.GetString("SelectLang_Description", resourceCulture); }
        }

        /// <summary>Lang_English</summary>
        public static string Lang_English
        {
            get { return ResourceManager.GetString("Lang_English", resourceCulture); }
        }

        /// <summary>Lang_Polish</summary>
        public static string Lang_Polish
        {
            get { return ResourceManager.GetString("Lang_Polish", resourceCulture); }
        }

        /// <summary>Lang_Romanian</summary>
        public static string Lang_Romanian
        {
            get { return ResourceManager.GetString("Lang_Romanian", resourceCulture); }
        }

        /// <summary>Lang_Gujarati</summary>
        public static string Lang_Gujarati
        {
            get { return ResourceManager.GetString("Lang_Gujarati", resourceCulture); }
        }

        /// <summary>Common_OK</summary>
        public static string Common_OK
        {
            get { return ResourceManager.GetString("Common_OK", resourceCulture); }
        }

        /// <summary>Common_Cancel</summary>
        public static string Common_Cancel
        {
            get { return ResourceManager.GetString("Common_Cancel", resourceCulture); }
        }

        /// <summary>Common_Loading</summary>
        public static string Common_Loading
        {
            get { return ResourceManager.GetString("Common_Loading", resourceCulture); }
        }

        /// <summary>Common_Error</summary>
        public static string Common_Error
        {
            get { return ResourceManager.GetString("Common_Error", resourceCulture); }
        }

        /// <summary>Common_Retry</summary>
        public static string Common_Retry
        {
            get { return ResourceManager.GetString("Common_Retry", resourceCulture); }
        }
    }
}
